// Code generated by protoc-gen-go.
// source: encryption.proto
// DO NOT EDIT!

/*
Package encryption is a generated protocol buffer package.

It is generated from these files:
	encryption.proto

It has these top-level messages:
	EncryptedReadRequest
	EncryptedReadResponse
	EncryptedWriteRequest
	EncryptedWriteResponse
*/
package encryption

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncryptedReadRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id  []byte `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *EncryptedReadRequest) Reset()                    { *m = EncryptedReadRequest{} }
func (m *EncryptedReadRequest) String() string            { return proto.CompactTextString(m) }
func (*EncryptedReadRequest) ProtoMessage()               {}
func (*EncryptedReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EncryptedReadResponse struct {
	Plaintext []byte `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
}

func (m *EncryptedReadResponse) Reset()                    { *m = EncryptedReadResponse{} }
func (m *EncryptedReadResponse) String() string            { return proto.CompactTextString(m) }
func (*EncryptedReadResponse) ProtoMessage()               {}
func (*EncryptedReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EncryptedWriteRequest struct {
	Plaintext []byte `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Id        []byte `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *EncryptedWriteRequest) Reset()                    { *m = EncryptedWriteRequest{} }
func (m *EncryptedWriteRequest) String() string            { return proto.CompactTextString(m) }
func (*EncryptedWriteRequest) ProtoMessage()               {}
func (*EncryptedWriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type EncryptedWriteResponse struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *EncryptedWriteResponse) Reset()                    { *m = EncryptedWriteResponse{} }
func (m *EncryptedWriteResponse) String() string            { return proto.CompactTextString(m) }
func (*EncryptedWriteResponse) ProtoMessage()               {}
func (*EncryptedWriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*EncryptedReadRequest)(nil), "EncryptedReadRequest")
	proto.RegisterType((*EncryptedReadResponse)(nil), "EncryptedReadResponse")
	proto.RegisterType((*EncryptedWriteRequest)(nil), "EncryptedWriteRequest")
	proto.RegisterType((*EncryptedWriteResponse)(nil), "EncryptedWriteResponse")
}

func init() { proto.RegisterFile("encryption.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xcd, 0x4b, 0x2e,
	0xaa, 0x2c, 0x28, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe0, 0x12,
	0x71, 0x85, 0x88, 0xa5, 0xa6, 0x04, 0xa5, 0x26, 0x02, 0x71, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90,
	0x00, 0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x88, 0x29, 0xc4,
	0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0x04, 0x16, 0x00, 0xb2, 0x94, 0x4c, 0xb9, 0x44, 0xd1, 0x74,
	0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xc9, 0x70, 0x71, 0x16, 0xe4, 0x24, 0x66, 0xe6, 0x95,
	0xa4, 0x56, 0x94, 0x40, 0x0d, 0x40, 0x08, 0x28, 0xb9, 0x22, 0x69, 0x0b, 0x2f, 0xca, 0x2c, 0x49,
	0x85, 0xd9, 0x88, 0x57, 0x1b, 0x86, 0xed, 0x5a, 0x5c, 0x62, 0xe8, 0xc6, 0x40, 0xad, 0xc7, 0x70,
	0x79, 0x12, 0x1b, 0xd8, 0xab, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0x8e, 0x9c, 0x58,
	0xfe, 0x00, 0x00, 0x00,
}
